name: Resize Poster Image

on:
  push:
    paths:
      - "poster.jpg"

jobs:
  resize-and-optimize:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    # do not run when workflow commits files
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Variants
        run: |
          # Create WebP versions for faster loading
          convert poster.* -quality 90 poster.webp
          convert poster.* -quality 90 -resize 375x poster-xs.webp
          convert poster.* -quality 90 -resize 768x poster-sm.webp
          convert poster.* -quality 90 -resize 1024x poster-md.webp
          convert poster.* -quality 90 -resize 1440x poster-lg.webp
          convert poster.* -quality 90 -resize 1920x poster-xl.webp

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update responsive images [skip ci]"
          file_pattern: "poster*.webp"
