name: Resize Poster Image

on:
  push:
    paths:
      - "poster.*" # matches any kind of image

jobs:
  resize-and-optimize:
    permissions:
      contents: write # allows commiting files from workflow
    runs-on: ubuntu-latest

    # do not run when workflow commits files
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Variants
        run: |

          # get new poster file
          NEW_POSTER =$(ls -t poster.* | head -1)

          # remove old poster file if new has different extension
          # for example, previously we had poster.jpg and now we have poster.png
          find . -maxdepth 1 -name "poster.*" ! -name "$NEW_POSTER" -delete

          # clear and re-create assets dir
          mkdir -p assets
          rm -f assets/poster*.webp

          # Create WebP versions for faster loading using imagemagick
          # and store them in the assets dir
          convert "$NEW_POSTER" -strip -quality 90 assets/poster.webp
          convert "$NEW_POSTER" -strip -quality 90 -resize 375x assets/poster-xs.webp
          convert "$NEW_POSTER" -strip -quality 90 -resize 768x assets/poster-sm.webp
          convert "$NEW_POSTER" -strip -quality 90 -resize 1024x assets/poster-md.webp
          convert "$NEW_POSTER" -strip -quality 90 -resize 1440x assets/poster-lg.webp
          convert "$NEW_POSTER" -strip -quality 90 -resize 1920x assets/poster-xl.webp

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update responsive images [skip ci]"
          file_pattern: "poster*. assets/poster*.webp "
